## Link a documentacion RNN de Pytorch, librerias y funciones a utilizar.

https://pytorch.org/docs/stable/generated/torch.nn.RNN.html#torch.nn.RNN

### Librerias y funciones comunes

In [1]:
# Librerias
import numpy as np
import torch


In [3]:
class SimpleRNN(torch.nn.Module):
  def __init__(self, input_size=1, hidden_size=1, num_layers=1):
    super().__init__()
    self.rnn = torch.nn.RNN(input_size, hidden_size, num_layers, batch_first=True)

  def forward(self, x):
    y, h = self.rnn(x)
    return y, h


In [4]:
def imp_param(model):
  print('-'*84)
  print('PARAMETROS DEL MODELO')
  print('-'*84)
  for name, param in model.named_parameters():
    if param.requires_grad:
      print('Nombre del parámetro: ')
      print(name)
      print('Tamaño del parámetro: ')
      print(param.data.shape)
      print()


In [6]:
def teoria(model, largo_entrada = 3, batch_size=1, input_size=1):
  print('-'*84)
  print('MODELO')
  print('-'*84)
  print(model)
  imp_param(model)

  # Generamos una entrada aleatoria para ver como responde la red
  # el tamaño de la entrada esa acorde a los tamaños que cargamos antes
  entrada = torch.rand(batch_size, largo_entrada, input_size)
  print('-'*84)
  print('ENTRADA')
  print('-'*84)
  print('entrada shape: ', entrada.shape)
  print(entrada)

  # le agrego la dimension del batch:
  #entrada = entrada[None, :]
  print()
  print('entrada con nuevas dimensiones [batch, Length, nr_features] ')
  print(entrada.shape)

  # Pasamos la entrada a la red
  y, h = model(entrada)
  print('-'*84)
  print('SALIDA')
  print('-'*84)
  print('salida de la red (output) (largo igual al input): ', y.shape)
  print(y)
  print()
  print('hidden red (solo ultimo hidden): ', h.shape)
  print(h)




### RNN simple

Veamos los parámetros del siguiente modelo con sus respectivas inputs y outputs:



![Red recurrente simple](https://docs.google.com/uc?id=15IXcZnzbVB-DlCPlne0eJWWRBcX2FPVy)

link:
https://drive.google.com/file/d/15IXcZnzbVB-DlCPlne0eJWWRBcX2FPVy/view?usp=


Parámetros/señales a ver su tamaño (agrege las necesarias):



```
# Entrada
x =

# hidden state
h =

# Salida
y =
h =

# parámetros
Wih =
Bih =

Whh =
Bhh =
```



In [7]:
input_size= 1
hidden_size= 1
num_layers= 1
largo_entrada = 5

model = SimpleRNN(input_size, hidden_size, num_layers)
teoria(model, largo_entrada)

------------------------------------------------------------------------------------
MODELO
------------------------------------------------------------------------------------
SimpleRNN(
  (rnn): RNN(1, 1, batch_first=True)
)
------------------------------------------------------------------------------------
PARAMETROS DEL MODELO
------------------------------------------------------------------------------------
Nombre del parámetro: 
rnn.weight_ih_l0
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.weight_hh_l0
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.bias_ih_l0
Tamaño del parámetro: 
torch.Size([1])

Nombre del parámetro: 
rnn.bias_hh_l0
Tamaño del parámetro: 
torch.Size([1])

------------------------------------------------------------------------------------
ENTRADA
------------------------------------------------------------------------------------
entrada shape:  torch.Size([1, 5, 1])
tensor([[[0.9175],
         [0.0280],
     

### RNN con hidden

Veamos los parámetros del siguiente modelo con sus respectivas inputs y outputs:



![Red recurrente simple](https://docs.google.com/uc?id=1pWM5wlqYX8HSiTXz_Gg7KSOzvcxAQeQF)

link:
https://drive.google.com/file/d/1pWM5wlqYX8HSiTXz_Gg7KSOzvcxAQeQF/view?usp=drive_link


Parámetros/señales a ver su tamaño (agrege las necesarias):


```
# Entrada
x =

# hidden state
h =

# Salida
y =
h =

# parámetros
Wih =
Bih =

Whh =
Bhh =
```

In [8]:
input_size= 1
hidden_size= 3
num_layers= 1
largo_entrada = 10

model = SimpleRNN(input_size, hidden_size, num_layers)
teoria(model, largo_entrada)

------------------------------------------------------------------------------------
MODELO
------------------------------------------------------------------------------------
SimpleRNN(
  (rnn): RNN(1, 3, batch_first=True)
)
------------------------------------------------------------------------------------
PARAMETROS DEL MODELO
------------------------------------------------------------------------------------
Nombre del parámetro: 
rnn.weight_ih_l0
Tamaño del parámetro: 
torch.Size([3, 1])

Nombre del parámetro: 
rnn.weight_hh_l0
Tamaño del parámetro: 
torch.Size([3, 3])

Nombre del parámetro: 
rnn.bias_ih_l0
Tamaño del parámetro: 
torch.Size([3])

Nombre del parámetro: 
rnn.bias_hh_l0
Tamaño del parámetro: 
torch.Size([3])

------------------------------------------------------------------------------------
ENTRADA
------------------------------------------------------------------------------------
entrada shape:  torch.Size([1, 10, 1])
tensor([[[0.9156],
         [0.8617],
    

### RNN con 2 layers


Veamos los parámetros del siguiente modelo con sus respectivas inputs y outputs:



![Red recurrente simple](https://docs.google.com/uc?id=1mOmacJg5qE2B7KtAsqd--iCNknyD3_5J)

link:
https://drive.google.com/file/d/1mOmacJg5qE2B7KtAsqd--iCNknyD3_5J/view?usp=drive_link


Parámetros/señales a ver su tamaño (agrege las necesarias):


```
# Entrada
x =

# hidden state
h_l0 =

# Salida
y =
h_l0 =
h_l1 =

# parámetros
Wih_l0 =
Bih_l0 =

Whh_l0 =
Bhh_l0 =

Wih_l1 =
Bih_l1 =

Whh_l1 =
Bhh_l1 =
```

In [16]:
input_size= 1
hidden_size= 1
num_layers= 2
largo_entrada = 7

model = SimpleRNN(input_size, hidden_size, num_layers)
teoria(model, largo_entrada)

------------------------------------------------------------------------------------
MODELO
------------------------------------------------------------------------------------
SimpleRNN(
  (rnn): RNN(1, 1, num_layers=2, batch_first=True)
)
------------------------------------------------------------------------------------
PARAMETROS DEL MODELO
------------------------------------------------------------------------------------
Nombre del parámetro: 
rnn.weight_ih_l0
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.weight_hh_l0
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.bias_ih_l0
Tamaño del parámetro: 
torch.Size([1])

Nombre del parámetro: 
rnn.bias_hh_l0
Tamaño del parámetro: 
torch.Size([1])

Nombre del parámetro: 
rnn.weight_ih_l1
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.weight_hh_l1
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.bias_ih_l1
Tamaño del parámetro: 
torch.Size([1])

N

### RNN con input mutivariable


Veamos los parámetros del siguiente modelo con sus respectivas inputs y outputs:



![Red recurrente simple](https://docs.google.com/uc?id=1z0h38RWgxbtrMUazdPHvK3KZTCZFfmJR)

link:
https://drive.google.com/file/d/1z0h38RWgxbtrMUazdPHvK3KZTCZFfmJR/view?usp=drive_link


Parámetros/señales a ver su tamaño (agrege las necesarias):


```
# Entrada
x =

# hidden state
h =

# Salida
y =
h =

# parámetros
Wih =
Bih =

Whh =
Bhh =
```

In [18]:
input_size= 3
hidden_size= 1
num_layers= 1
largo_entrada = 11

model = SimpleRNN(input_size, hidden_size, num_layers)
teoria(model, largo_entrada, input_size= 3)

------------------------------------------------------------------------------------
MODELO
------------------------------------------------------------------------------------
SimpleRNN(
  (rnn): RNN(3, 1, batch_first=True)
)
------------------------------------------------------------------------------------
PARAMETROS DEL MODELO
------------------------------------------------------------------------------------
Nombre del parámetro: 
rnn.weight_ih_l0
Tamaño del parámetro: 
torch.Size([1, 3])

Nombre del parámetro: 
rnn.weight_hh_l0
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.bias_ih_l0
Tamaño del parámetro: 
torch.Size([1])

Nombre del parámetro: 
rnn.bias_hh_l0
Tamaño del parámetro: 
torch.Size([1])

------------------------------------------------------------------------------------
ENTRADA
------------------------------------------------------------------------------------
entrada shape:  torch.Size([1, 11, 3])
tensor([[[0.3093, 0.1123, 0.8921],
       

In [20]:
teoria(model, 30, input_size= 3)

------------------------------------------------------------------------------------
MODELO
------------------------------------------------------------------------------------
SimpleRNN(
  (rnn): RNN(3, 1, batch_first=True)
)
------------------------------------------------------------------------------------
PARAMETROS DEL MODELO
------------------------------------------------------------------------------------
Nombre del parámetro: 
rnn.weight_ih_l0
Tamaño del parámetro: 
torch.Size([1, 3])

Nombre del parámetro: 
rnn.weight_hh_l0
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.bias_ih_l0
Tamaño del parámetro: 
torch.Size([1])

Nombre del parámetro: 
rnn.bias_hh_l0
Tamaño del parámetro: 
torch.Size([1])

------------------------------------------------------------------------------------
ENTRADA
------------------------------------------------------------------------------------
entrada shape:  torch.Size([1, 30, 3])
tensor([[[0.3344, 0.6720, 0.9901],
       

### RNN con varias cosas y batch size!

In [17]:
input_size= 2
hidden_size=7
num_layers=2
largo_entrada = 5
batch_size=3

model = SimpleRNN(input_size, hidden_size, num_layers)
teoria(model, largo_entrada, batch_size, input_size= 2)

------------------------------------------------------------------------------------
MODELO
------------------------------------------------------------------------------------
SimpleRNN(
  (rnn): RNN(2, 7, num_layers=2, batch_first=True)
)
------------------------------------------------------------------------------------
PARAMETROS DEL MODELO
------------------------------------------------------------------------------------
Nombre del parámetro: 
rnn.weight_ih_l0
Tamaño del parámetro: 
torch.Size([7, 2])

Nombre del parámetro: 
rnn.weight_hh_l0
Tamaño del parámetro: 
torch.Size([7, 7])

Nombre del parámetro: 
rnn.bias_ih_l0
Tamaño del parámetro: 
torch.Size([7])

Nombre del parámetro: 
rnn.bias_hh_l0
Tamaño del parámetro: 
torch.Size([7])

Nombre del parámetro: 
rnn.weight_ih_l1
Tamaño del parámetro: 
torch.Size([7, 7])

Nombre del parámetro: 
rnn.weight_hh_l1
Tamaño del parámetro: 
torch.Size([7, 7])

Nombre del parámetro: 
rnn.bias_ih_l1
Tamaño del parámetro: 
torch.Size([7])

N

## EJERCICIO 1 - Complete el cuadro del powerpoint paras los siguientes 3 ejemplos:
```
EJEMPLO A
input_size = 2
batch_size = 16
hidden_size = 24
num_layer = 3
```

```
EJEMPLO B
input_size = 6
batch_size = 16
hidden_size = 24
num_layer = 1
```
```
EJEMPLO C
input_size = 10
batch_size = 64
hidden_size = 64
num_laye = 4
```

## EJERCICIO 2 - Implementar una RNN para clasificación de 5 clases:
- `input size = 2`.
- `hidden size= 40`.
- `num_layers = 2`.
- Agregar una `fully conected` al final con `n_out = nro clases`.
- Tomar como `input` de la `fc` el estado final de la rnn.
- Agregar por último una `softmax` para leer probabilidades.
- Probar funcionamiento del modelo haciendo un forward con un número rand sin entrenar la red.


![Red recurrente simple](https://docs.google.com/uc?id=1llbd9OArPRMAReI730fEtfmsN8VX3QfL)

link:
https://drive.google.com/file/d/1llbd9OArPRMAReI730fEtfmsN8VX3QfL/view?usp=drive_link