## Link a documentacion RNN de Pytorch, librerias y funciones a utilizar.

https://pytorch.org/docs/stable/generated/torch.nn.RNN.html#torch.nn.RNN

### Librerias y funciones comunes

In [1]:
# Librerias
import numpy as np
import torch


In [2]:
class SimpleRNN(torch.nn.Module):
  def __init__(self, input_size=1, hidden_size=1, num_layers=1):
    super().__init__()
    self.rnn = torch.nn.RNN(input_size, hidden_size, num_layers, batch_first=True)

  def forward(self, x):
    x, h = self.rnn(x) 
    return x, h


In [3]:
def imp_param(model):
  print('-'*84)
  print('PARAMETROS DEL MODELO')
  print('-'*84)
  for name, param in model.named_parameters():
    if param.requires_grad: 
      print('Nombre del parámetro: ')
      print(name)
      print('Tamaño del parámetro: ')
      print(param.data.shape)
      print()


In [4]:
def teoria(model, largo_entrada = 3, batch_size=1):
  print('-'*84)
  print('MODELO')
  print('-'*84)
  print(model)
  imp_param(model)

  # Generamos una entrada aleatoria para ver como responde la red
  # el tamaño de la entrada esa acorde a los tamaños que cargamos antes
  entrada = torch.rand(batch_size, largo_entrada, input_size)
  print('-'*84)
  print('ENTRADA')
  print('-'*84)
  print('entrada shape: ', entrada.shape)
  print(entrada)

  # le agrego la dimension del batch:
  #entrada = entrada[None, :]
  print()
  print('entrada con nuevas dimensiones [batch, Length, nr_features] ')
  print(entrada.shape)

  # Pasamos la entrada a la red
  o, h = model(entrada)
  print('-'*84)
  print('SALIDA')
  print('-'*84)
  print('salida de la red (output) (largo igual al input): ', o.shape)
  print(o)
  print()
  print('hidden red (solo ultimo hidden): ', h.shape)
  print(h)




### RNN simple

In [5]:
input_size= 1
hidden_size= 1
num_layers= 1
largo_entrada = 7

model = SimpleRNN(input_size, hidden_size, num_layers)
teoria(model, largo_entrada)

------------------------------------------------------------------------------------
MODELO
------------------------------------------------------------------------------------
SimpleRNN(
  (rnn): RNN(1, 1, batch_first=True)
)
------------------------------------------------------------------------------------
PARAMETROS DEL MODELO
------------------------------------------------------------------------------------
Nombre del parámetro: 
rnn.weight_ih_l0
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.weight_hh_l0
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.bias_ih_l0
Tamaño del parámetro: 
torch.Size([1])

Nombre del parámetro: 
rnn.bias_hh_l0
Tamaño del parámetro: 
torch.Size([1])

------------------------------------------------------------------------------------
ENTRADA
------------------------------------------------------------------------------------
entrada shape:  torch.Size([1, 7, 1])
tensor([[[0.1326],
         [0.5940],
     

### RNN con hidden

In [6]:
input_size= 1
hidden_size= 3
num_layers= 1
largo_entrada = 10

model = SimpleRNN(input_size, hidden_size, num_layers)
teoria(model, largo_entrada)

------------------------------------------------------------------------------------
MODELO
------------------------------------------------------------------------------------
SimpleRNN(
  (rnn): RNN(1, 3, batch_first=True)
)
------------------------------------------------------------------------------------
PARAMETROS DEL MODELO
------------------------------------------------------------------------------------
Nombre del parámetro: 
rnn.weight_ih_l0
Tamaño del parámetro: 
torch.Size([3, 1])

Nombre del parámetro: 
rnn.weight_hh_l0
Tamaño del parámetro: 
torch.Size([3, 3])

Nombre del parámetro: 
rnn.bias_ih_l0
Tamaño del parámetro: 
torch.Size([3])

Nombre del parámetro: 
rnn.bias_hh_l0
Tamaño del parámetro: 
torch.Size([3])

------------------------------------------------------------------------------------
ENTRADA
------------------------------------------------------------------------------------
entrada shape:  torch.Size([1, 10, 1])
tensor([[[0.1498],
         [0.7185],
    

### RNN con 2 layers

In [7]:
input_size= 1
hidden_size= 1
num_layers= 4
largo_entrada = 7

model = SimpleRNN(input_size, hidden_size, num_layers)
teoria(model, largo_entrada)

------------------------------------------------------------------------------------
MODELO
------------------------------------------------------------------------------------
SimpleRNN(
  (rnn): RNN(1, 1, num_layers=4, batch_first=True)
)
------------------------------------------------------------------------------------
PARAMETROS DEL MODELO
------------------------------------------------------------------------------------
Nombre del parámetro: 
rnn.weight_ih_l0
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.weight_hh_l0
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.bias_ih_l0
Tamaño del parámetro: 
torch.Size([1])

Nombre del parámetro: 
rnn.bias_hh_l0
Tamaño del parámetro: 
torch.Size([1])

Nombre del parámetro: 
rnn.weight_ih_l1
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.weight_hh_l1
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.bias_ih_l1
Tamaño del parámetro: 
torch.Size([1])

N

### RNN con input mutivariable

In [8]:
input_size= 3
hidden_size= 1
num_layers= 1
largo_entrada = 11

model = SimpleRNN(input_size, hidden_size, num_layers)
teoria(model, largo_entrada)

------------------------------------------------------------------------------------
MODELO
------------------------------------------------------------------------------------
SimpleRNN(
  (rnn): RNN(3, 1, batch_first=True)
)
------------------------------------------------------------------------------------
PARAMETROS DEL MODELO
------------------------------------------------------------------------------------
Nombre del parámetro: 
rnn.weight_ih_l0
Tamaño del parámetro: 
torch.Size([1, 3])

Nombre del parámetro: 
rnn.weight_hh_l0
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.bias_ih_l0
Tamaño del parámetro: 
torch.Size([1])

Nombre del parámetro: 
rnn.bias_hh_l0
Tamaño del parámetro: 
torch.Size([1])

------------------------------------------------------------------------------------
ENTRADA
------------------------------------------------------------------------------------
entrada shape:  torch.Size([1, 11, 3])
tensor([[[0.5764, 0.2597, 0.5790],
       

### RNN con varias cosas

In [10]:
input_size= 9
hidden_size=7
num_layers=2
largo_entrada = 5
batch_size=3

model = SimpleRNN(input_size, hidden_size, num_layers)
teoria(model, largo_entrada, batch_size)  

------------------------------------------------------------------------------------
MODELO
------------------------------------------------------------------------------------
SimpleRNN(
  (rnn): RNN(9, 7, num_layers=2, batch_first=True)
)
------------------------------------------------------------------------------------
PARAMETROS DEL MODELO
------------------------------------------------------------------------------------
Nombre del parámetro: 
rnn.weight_ih_l0
Tamaño del parámetro: 
torch.Size([7, 9])

Nombre del parámetro: 
rnn.weight_hh_l0
Tamaño del parámetro: 
torch.Size([7, 7])

Nombre del parámetro: 
rnn.bias_ih_l0
Tamaño del parámetro: 
torch.Size([7])

Nombre del parámetro: 
rnn.bias_hh_l0
Tamaño del parámetro: 
torch.Size([7])

Nombre del parámetro: 
rnn.weight_ih_l1
Tamaño del parámetro: 
torch.Size([7, 7])

Nombre del parámetro: 
rnn.weight_hh_l1
Tamaño del parámetro: 
torch.Size([7, 7])

Nombre del parámetro: 
rnn.bias_ih_l1
Tamaño del parámetro: 
torch.Size([7])

N

## EJERCICIO 1 - Complete el cuadro del powerpoint paras los siguientes 3 ejemplos:
```
EJEMPLO A
input_size = 2
batch_size = 16
hidden_size = 24
num_layer = 3
```

```
EJEMPLO B
input_size = 6
batch_size = 16
hidden_size = 24
num_layer = 1
```
```
EJEMPLO C
input_size = 10
batch_size = 64
hidden_size = 64
num_laye = 4
```

## EJERCICIO 2 - Implementar una RNN para clasificación de 5 clases:
- `input size = 2`.
- `hidden size= 40`.
- `num_layers = 1`.
- Agregar una `fully conected` al final con `n_out = nro clases`.
- Tomar como `input` de la `fc` el estado final de la rnn.
- Agregar por último una `softmax` para leer probabilidades.
- Probar funcionamiento del modelo haciendo un forward con un número rand sin entrenar la red.

## RNN compuesta por 1 RNN  + 1 FC + 1 RNN
usar clase SimpleRNN_2

es una red propuesta por un alumno

In [ ]:
class SimpleRNN_2(torch.nn.Module):
  def __init__(self, input_size=1, hidden_size=1, num_layers=1, out_fc=2, hidden_size2=3):
    super().__init__()
    self.rnn1 = torch.nn.RNN(input_size, hidden_size, num_layers, batch_first=True)
    self.fc = torch.nn.Linear(hidden_size, out_fc )
    self.rnn2 = torch.nn.RNN(out_fc, hidden_size2, num_layers, batch_first=True)
  
  def forward(self, x):
    x, h = self.rnn1(x)
    o_fc = self.fc(h) # le paso el hidden state final de la rrn1
                      # esto será de largo igual al numero de hidden
                      # tiene sentido pasar el hidden final por que tendrá
                      # la información de la secuencia en entrada ya "almacenada"
    x2, h2 = self.rnn2(o_fc)
    return x2, h2


In [ ]:
input_size= 3 # 3 features
hidden_size= 5 # 5 hidden de la 1ra RNN
num_layers= 1 # num layer 1er RNN. OJO! si aumentan las layer, la salida h
              # últumo hidden, devuelve el último hidden de cada capa!

out_fc = 2 # número de salidas de la fc
hidden_size2 = 3 # numero de hidden de la 2da RNN...
                # el número de input (features) de la RNN2 es de 1 la salida
                # de la fc es de prof y largo = out_fc

largo_entrada = 7

model = SimpleRNN_2(input_size, hidden_size, num_layers, out_fc, hidden_size2)
teoria(model, largo_entrada)

------------------------------------------------------------------------------------
MODELO
------------------------------------------------------------------------------------
SimpleRNN_2(
  (rnn1): RNN(3, 5, batch_first=True)
  (fc): Linear(in_features=5, out_features=2, bias=True)
  (rnn2): RNN(2, 3, batch_first=True)
)
------------------------------------------------------------------------------------
PARAMETROS DEL MODELO
------------------------------------------------------------------------------------
Nombre del parámetro: 
rnn1.weight_ih_l0
Tamaño del parámetro: 
torch.Size([5, 3])

Nombre del parámetro: 
rnn1.weight_hh_l0
Tamaño del parámetro: 
torch.Size([5, 5])

Nombre del parámetro: 
rnn1.bias_ih_l0
Tamaño del parámetro: 
torch.Size([5])

Nombre del parámetro: 
rnn1.bias_hh_l0
Tamaño del parámetro: 
torch.Size([5])

Nombre del parámetro: 
fc.weight
Tamaño del parámetro: 
torch.Size([2, 5])

Nombre del parámetro: 
fc.bias
Tamaño del parámetro: 
torch.Size([2])

Nombre del