## Link a documentacion RNN de Pytorch, librerias y funciones a utilizar.

https://pytorch.org/docs/stable/generated/torch.nn.RNN.html#torch.nn.RNN

### Librerias y funciones comunes

In [1]:
# Librerias
import numpy as np
import torch


In [2]:
# clase básica para comprender cómo funciona la RNN
class SimpleRNN(torch.nn.Module):
  def __init__(self, input_size=1, hidden_size=1, num_layers=1):
    super().__init__()
    self.rnn = torch.nn.RNN(input_size, hidden_size, num_layers, batch_first=True)
# solamente definimos los argumentos más importantes, pero tiene todos estos:
#   input_size int
#   hidden_size int
#   num_layers=1
#   nonlinearity='tanh' or 'relu'
#   bias=True
#   batch_first=False
#   dropout=0.0
#   bidirectional=False
#   device=None
#   dtype=None

  def forward(self, x):
    y, h = self.rnn(x)
    # como salida la RNN entrega el hidden state a lo largo del tiempo (salida y)
    # y el hidden state final (salida h)
    return y, h


In [3]:
# función que vamos a utilizar para ver los nombres de los parámetros
# de nuestra red y sus dimensiones

def imp_param(model):
  print('-'*84)
  print('PARAMETROS DEL MODELO')
  print('-'*84)
  for name, param in model.named_parameters():
    if param.requires_grad:
      print('Nombre del parámetro: ')
      print(name)
      print('Tamaño del parámetro: ')
      print(param.data.shape)
      print()


In [4]:
# función para usar en la teoría
# se le pasa un modelo de RNN, y los valores que queremos probrar en un paso forward
#   largo_entrada
#   batch_size
#   input_size

# la función imprime el modelo y sus parámetros
# luego, genera una señal aleatoria para probar un forward y ver las dimensiones
# de las salidas.

def teoria(model, largo_entrada = 3, batch_size=1, input_size=1):
  print('-'*84)
  print('MODELO')
  print('-'*84)
  print(model)
  imp_param(model)

  # Generamos una entrada aleatoria para ver como responde la red
  # el tamaño de la entrada esa acorde a los tamaños que cargamos antes
  entrada = torch.rand(batch_size, largo_entrada, input_size)
  print('-'*84)
  print('ENTRADA')
  print('-'*84)
  print('entrada shape: ', entrada.shape)
  print(entrada)

  # le agrego la dimension del batch:
  #entrada = entrada[None, :]
  print()
  print('entrada con nuevas dimensiones [batch, Length, nr_features] ')
  print(entrada.shape)

  # Pasamos la entrada a la red
  o, h = model(entrada)
  print('-'*84)
  print('SALIDA')
  print('-'*84)
  print('salida de la red (output) (largo igual al input): ', o.shape)
  print(o)
  print()
  print('hidden red (solo ultimo hidden): ', h.shape)
  print(h)


## EJERCICIO 1 - Complete el cuadro del powerpoint paras los siguientes 3 ejemplos:





```
EJEMPLO A
input_size = 2
batch_size = 16
hidden_size = 24
num_layer = 3
```

In [5]:
input_size= 1
batch_size=4
hidden_size=1
num_layers=1

largo_entrada = 3


model = SimpleRNN(input_size, hidden_size, num_layers)
teoria(model, largo_entrada, batch_size, input_size)

------------------------------------------------------------------------------------
MODELO
------------------------------------------------------------------------------------
SimpleRNN(
  (rnn): RNN(1, 1, batch_first=True)
)
------------------------------------------------------------------------------------
PARAMETROS DEL MODELO
------------------------------------------------------------------------------------
Nombre del parámetro: 
rnn.weight_ih_l0
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.weight_hh_l0
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.bias_ih_l0
Tamaño del parámetro: 
torch.Size([1])

Nombre del parámetro: 
rnn.bias_hh_l0
Tamaño del parámetro: 
torch.Size([1])

------------------------------------------------------------------------------------
ENTRADA
------------------------------------------------------------------------------------
entrada shape:  torch.Size([4, 3, 1])
tensor([[[0.5180],
         [0.8032],
     

```
EJEMPLO B
input_size = 6
batch_size = 16
hidden_size = 24
num_layer = 1
```

In [6]:
input_size= 1
batch_size=4
hidden_size=3
num_layers=1

largo_entrada = 5

model = SimpleRNN(input_size, hidden_size, num_layers)
teoria(model, largo_entrada, batch_size)

------------------------------------------------------------------------------------
MODELO
------------------------------------------------------------------------------------
SimpleRNN(
  (rnn): RNN(1, 3, batch_first=True)
)
------------------------------------------------------------------------------------
PARAMETROS DEL MODELO
------------------------------------------------------------------------------------
Nombre del parámetro: 
rnn.weight_ih_l0
Tamaño del parámetro: 
torch.Size([3, 1])

Nombre del parámetro: 
rnn.weight_hh_l0
Tamaño del parámetro: 
torch.Size([3, 3])

Nombre del parámetro: 
rnn.bias_ih_l0
Tamaño del parámetro: 
torch.Size([3])

Nombre del parámetro: 
rnn.bias_hh_l0
Tamaño del parámetro: 
torch.Size([3])

------------------------------------------------------------------------------------
ENTRADA
------------------------------------------------------------------------------------
entrada shape:  torch.Size([4, 5, 1])
tensor([[[0.6378],
         [0.7382],
     

```
EJEMPLO C
input_size = 10
batch_size = 64
hidden_size = 64
num_layer = 4
```

In [7]:
input_size= 5
batch_size=4
hidden_size=1
num_layers=1

largo_entrada = 3

model = SimpleRNN(input_size, hidden_size, num_layers)
teoria(model, largo_entrada, batch_size, input_size=input_size)

------------------------------------------------------------------------------------
MODELO
------------------------------------------------------------------------------------
SimpleRNN(
  (rnn): RNN(5, 1, batch_first=True)
)
------------------------------------------------------------------------------------
PARAMETROS DEL MODELO
------------------------------------------------------------------------------------
Nombre del parámetro: 
rnn.weight_ih_l0
Tamaño del parámetro: 
torch.Size([1, 5])

Nombre del parámetro: 
rnn.weight_hh_l0
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.bias_ih_l0
Tamaño del parámetro: 
torch.Size([1])

Nombre del parámetro: 
rnn.bias_hh_l0
Tamaño del parámetro: 
torch.Size([1])

------------------------------------------------------------------------------------
ENTRADA
------------------------------------------------------------------------------------
entrada shape:  torch.Size([4, 3, 5])
tensor([[[3.3629e-01, 4.7462e-01, 7.4148e-0

In [8]:
model.rnn.weight_ih_l0

Parameter containing:
tensor([[ 0.0854,  0.9726, -0.4207, -0.6994,  0.9870]], requires_grad=True)

## EJERCICIO 2 - Implementar una RNN para clasificación de 5 clases dada una secuencia de datos:
- `input size = 2`.
- `hidden size= 40`.
- `num_layers = 2`.
- Agregar una `fully conected` al final con `n_out = nro clases`.
- Tomar como `input` de la `fc` el estado final de la rnn.
- Agregar por último una `softmax` para leer probabilidades.
- Probar funcionamiento del modelo haciendo un forward con un número rand sin entrenar la red.


![Red recurrente simple](https://docs.google.com/uc?id=1llbd9OArPRMAReI730fEtfmsN8VX3QfL)

link:
https://drive.google.com/file/d/1llbd9OArPRMAReI730fEtfmsN8VX3QfL/view?usp=drive_link

In [17]:
class RNN_clas(torch.nn.Module):
  def __init__(self, input_size=2, hidden_size=40, num_layers=2, out_fc=5):
    super().__init__()
    self.rnn1 = torch.nn.RNN(input_size, hidden_size, num_layers, batch_first=True)
    self.fc = torch.nn.Linear(hidden_size, out_fc )

  def forward(self, x):
    x, h = self.rnn1(x)
    o_fc = self.fc(x[:,-1]) # le paso el hidden state final de la rnn1
                      # esto será de largo igual al numero de hidden
                      # tiene sentido pasar el hidden final por que tendrá
                      # la información de la secuencia en entrada ya "almacenada"
    o_fc_prob = torch.softmax(o_fc, 1)
    return o_fc_prob, o_fc_prob # acá repito la salida ya que mi funcion "teoria"
                                # espera que el modelo arroje 2 salidas.


In [18]:
input_size= 2 # 2 features
hidden_size= 40 # 40 hidden de la 1ra RNN
num_layers= 2 # num layer 1er RNN. OJO! si aumentan las layer, la salida h
              # último hidden, devuelve el último hidden de cada capa!

out_fc = 5 # número de salidas de la fc (numero de clases)

batch_size = 3

largo_entrada = 5

modelo_clas = RNN_clas(input_size, hidden_size, num_layers, out_fc)
teoria(modelo_clas, largo_entrada, batch_size, input_size)

------------------------------------------------------------------------------------
MODELO
------------------------------------------------------------------------------------
RNN_clas(
  (rnn1): RNN(2, 40, num_layers=2, batch_first=True)
  (fc): Linear(in_features=40, out_features=5, bias=True)
)
------------------------------------------------------------------------------------
PARAMETROS DEL MODELO
------------------------------------------------------------------------------------
Nombre del parámetro: 
rnn1.weight_ih_l0
Tamaño del parámetro: 
torch.Size([40, 2])

Nombre del parámetro: 
rnn1.weight_hh_l0
Tamaño del parámetro: 
torch.Size([40, 40])

Nombre del parámetro: 
rnn1.bias_ih_l0
Tamaño del parámetro: 
torch.Size([40])

Nombre del parámetro: 
rnn1.bias_hh_l0
Tamaño del parámetro: 
torch.Size([40])

Nombre del parámetro: 
rnn1.weight_ih_l1
Tamaño del parámetro: 
torch.Size([40, 40])

Nombre del parámetro: 
rnn1.weight_hh_l1
Tamaño del parámetro: 
torch.Size([40, 40])

Nombr

### probamos ahora con secuencias mas largas y vemos que todo funciona igual

In [20]:
teoria(modelo_clas, largo_entrada=2, batch_size=4, input_size=2)

------------------------------------------------------------------------------------
MODELO
------------------------------------------------------------------------------------
RNN_clas(
  (rnn1): RNN(2, 40, num_layers=2, batch_first=True)
  (fc): Linear(in_features=40, out_features=5, bias=True)
)
------------------------------------------------------------------------------------
PARAMETROS DEL MODELO
------------------------------------------------------------------------------------
Nombre del parámetro: 
rnn1.weight_ih_l0
Tamaño del parámetro: 
torch.Size([40, 2])

Nombre del parámetro: 
rnn1.weight_hh_l0
Tamaño del parámetro: 
torch.Size([40, 40])

Nombre del parámetro: 
rnn1.bias_ih_l0
Tamaño del parámetro: 
torch.Size([40])

Nombre del parámetro: 
rnn1.bias_hh_l0
Tamaño del parámetro: 
torch.Size([40])

Nombre del parámetro: 
rnn1.weight_ih_l1
Tamaño del parámetro: 
torch.Size([40, 40])

Nombre del parámetro: 
rnn1.weight_hh_l1
Tamaño del parámetro: 
torch.Size([40, 40])

Nombr

### test de FC sin tomar último histórico

Ahora modificamos la clase, para que la FC procese la secuencia entera...

In [21]:
class RNN_clas_2(torch.nn.Module):
  def __init__(self, input_size=2, hidden_size=40, num_layers=2, out_fc=5):
    super().__init__()
    self.rnn1 = torch.nn.RNN(input_size, hidden_size, num_layers, batch_first=True)
    self.fc = torch.nn.Linear(hidden_size, out_fc )

  def forward(self, x):
    x, h = self.rnn1(x)
    # X tiene size = [ batch x largo_señal x numero_hiden] =  ejemplo [3,7,40]
    o_fc = self.fc(x) # ACA CAMBIO!
                      # le paso TODO el hidden state de la rrn1 a la FC
                      # esto será de largo igual al numero de muestras (largo de señal)
                      # y al número de hidden de la última capa
                      # es como que esté calculando la probabilidad de las clases
                      # para cada instante de tiempo (quizas no tenga sentido)
    o_fc_prob = torch.softmax(o_fc, 1)
    return o_fc_prob, o_fc_prob # acá repito la salida ya que mi funcion "teoria"
                                # espera que el modelo arroje 2 salidas.


In [23]:
input_size= 2 # 2 features
hidden_size= 3 # 3 hidden de la 1ra RNN
num_layers= 2 # num layer 1er RNN. OJO! si aumentan las layer, la salida h
              # último hidden, devuelve el último hidden de cada capa!

out_fc = 5 # número de salidas de la fc (numero de clases)

batch_size = 3

largo_entrada = 7

modelo_clas_2 = RNN_clas_2(input_size, hidden_size, num_layers, out_fc)
teoria(modelo_clas_2, largo_entrada, batch_size, input_size)

------------------------------------------------------------------------------------
MODELO
------------------------------------------------------------------------------------
RNN_clas_2(
  (rnn1): RNN(2, 3, num_layers=2, batch_first=True)
  (fc): Linear(in_features=3, out_features=5, bias=True)
)
------------------------------------------------------------------------------------
PARAMETROS DEL MODELO
------------------------------------------------------------------------------------
Nombre del parámetro: 
rnn1.weight_ih_l0
Tamaño del parámetro: 
torch.Size([3, 2])

Nombre del parámetro: 
rnn1.weight_hh_l0
Tamaño del parámetro: 
torch.Size([3, 3])

Nombre del parámetro: 
rnn1.bias_ih_l0
Tamaño del parámetro: 
torch.Size([3])

Nombre del parámetro: 
rnn1.bias_hh_l0
Tamaño del parámetro: 
torch.Size([3])

Nombre del parámetro: 
rnn1.weight_ih_l1
Tamaño del parámetro: 
torch.Size([3, 3])

Nombre del parámetro: 
rnn1.weight_hh_l1
Tamaño del parámetro: 
torch.Size([3, 3])

Nombre del par

## RNN compuesta por 1 RNN  + 1 FC + 1 RNN
usar clase RNN_alumno

es una red propuesta por un alumno

In [24]:
class RNN_alumno(torch.nn.Module):
  def __init__(self, input_size=1, hidden_size=1, num_layers=1, out_fc=2, hidden_size2=3):
    super().__init__()
    self.rnn1 = torch.nn.RNN(input_size, hidden_size, num_layers, batch_first=True)
    self.fc = torch.nn.Linear(hidden_size, out_fc )
    self.rnn2 = torch.nn.RNN(out_fc, hidden_size2, num_layers, batch_first=True)

  def forward(self, x):
    x, h = self.rnn1(x)
    o_fc = self.fc(h) # le paso el hidden state final de la rrn1
                      # esto será de largo igual al numero de hidden
                      # tiene sentido pasar el hidden final por que tendrá
                      # la información de la secuencia en entrada ya "almacenada"
    x2, h2 = self.rnn2(o_fc)
    return x2, h2


In [25]:
input_size= 3 # 3 features
hidden_size= 5 # 5 hidden de la 1ra RNN
num_layers= 1 # num layer 1er RNN. OJO! si aumentan las layer, la salida h
              # último hidden, devuelve el último hidden de cada capa!

out_fc = 2 # número de salidas de la fc
hidden_size2 = 3 # numero de hidden de la 2da RNN...
                # el número de input (features) de la RNN2 es de 1 la salida
                # de la fc es de prof y largo = out_fc

largo_entrada = 7

modelo_alumno = RNN_alumno(input_size, hidden_size, num_layers, out_fc, hidden_size2)
teoria(modelo_alumno, largo_entrada, batch_size, input_size)

------------------------------------------------------------------------------------
MODELO
------------------------------------------------------------------------------------
RNN_alumno(
  (rnn1): RNN(3, 5, batch_first=True)
  (fc): Linear(in_features=5, out_features=2, bias=True)
  (rnn2): RNN(2, 3, batch_first=True)
)
------------------------------------------------------------------------------------
PARAMETROS DEL MODELO
------------------------------------------------------------------------------------
Nombre del parámetro: 
rnn1.weight_ih_l0
Tamaño del parámetro: 
torch.Size([5, 3])

Nombre del parámetro: 
rnn1.weight_hh_l0
Tamaño del parámetro: 
torch.Size([5, 5])

Nombre del parámetro: 
rnn1.bias_ih_l0
Tamaño del parámetro: 
torch.Size([5])

Nombre del parámetro: 
rnn1.bias_hh_l0
Tamaño del parámetro: 
torch.Size([5])

Nombre del parámetro: 
fc.weight
Tamaño del parámetro: 
torch.Size([2, 5])

Nombre del parámetro: 
fc.bias
Tamaño del parámetro: 
torch.Size([2])

Nombre del 