## Link a documentacion RNN de Pytorch, librerias y funciones a utilizar.

https://pytorch.org/docs/stable/generated/torch.nn.RNN.html#torch.nn.RNN

### Librerias y funciones comunes

In [1]:
# Librerias
import numpy as np
import torch


In [2]:
# clase básica para comprender cómo funciona la RNN
class SimpleRNN(torch.nn.Module):
  def __init__(self, input_size=1, hidden_size=1, num_layers=1):
    super().__init__()
    self.rnn = torch.nn.RNN(input_size, hidden_size, num_layers, batch_first=True)
# solamente definimos los argumentos más importantes, pero tiene todos estos:
#   input_size int
#   hidden_size int
#   num_layers=1
#   nonlinearity='tanh' or 'relu'
#   bias=True
#   batch_first=False
#   dropout=0.0
#   bidirectional=False
#   device=None
#   dtype=None

  def forward(self, x):
    y, h = self.rnn(x)
    # como salida la RNN entrega el hidden state a lo largo del tiempo (salida y)
    # y el hidden state final (salida h)
    return y, h


In [3]:
# función que vamos a utilizar para ver los nombres de los parámetros
# de nuestra red y sus dimensiones

def imp_param(model):
  print('-'*84)
  print('PARAMETROS DEL MODELO')
  print('-'*84)
  for name, param in model.named_parameters():
    if param.requires_grad:
      print('Nombre del parámetro: ')
      print(name)
      print('Tamaño del parámetro: ')
      print(param.data.shape)
      print()


In [4]:
# función para usar en la teoría
# se le pasa un modelo de RNN, y los valores que queremos probrar en un paso forward
#   largo_entrada
#   batch_size
#   input_size

# la función imprime el modelo y sus parámetros
# luego, genera una señal aleatoria para probar un forward y ver las dimensiones
# de las salidas.

def teoria(model, largo_entrada = 3, batch_size=1, input_size=1):
  print('-'*84)
  print('MODELO')
  print('-'*84)
  print(model)
  imp_param(model)

  # Generamos una entrada aleatoria para ver como responde la red
  # el tamaño de la entrada esa acorde a los tamaños que cargamos antes
  entrada = torch.rand(batch_size, largo_entrada, input_size)
  print('-'*84)
  print('ENTRADA')
  print('-'*84)
  print('entrada shape: ', entrada.shape)
  print(entrada)


  # Pasamos la entrada a la red
  y, h = model(entrada)
  print('-'*84)
  print('SALIDA')
  print('-'*84)
  print('salida de la red (output) (largo igual al input): ', y.shape)
  print(y)
  print()
  print('hidden red (solo ultimo hidden): ', h.shape)
  print(h)

### RNN simple

Veamos los parámetros del siguiente modelo con sus respectivas inputs y outputs:



![Red recurrente simple](https://docs.google.com/uc?id=15IXcZnzbVB-DlCPlne0eJWWRBcX2FPVy)

link:
https://drive.google.com/file/d/15IXcZnzbVB-DlCPlne0eJWWRBcX2FPVy/view?usp=


Parámetros/señales a ver su tamaño (agrege las necesarias):



```
# Entrada
x =

# hidden state
h =

# Salida
y =
h =

# parámetros
Wih =
Bih =

Whh =
Bhh =
```



In [10]:
input_size= 1
hidden_size= 1
num_layers= 1
largo_entrada = 7

model = SimpleRNN(input_size, hidden_size, num_layers)
teoria(model, largo_entrada)

------------------------------------------------------------------------------------
MODELO
------------------------------------------------------------------------------------
SimpleRNN(
  (rnn): RNN(1, 1, batch_first=True)
)
------------------------------------------------------------------------------------
PARAMETROS DEL MODELO
------------------------------------------------------------------------------------
Nombre del parámetro: 
rnn.weight_ih_l0
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.weight_hh_l0
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.bias_ih_l0
Tamaño del parámetro: 
torch.Size([1])

Nombre del parámetro: 
rnn.bias_hh_l0
Tamaño del parámetro: 
torch.Size([1])

------------------------------------------------------------------------------------
ENTRADA
------------------------------------------------------------------------------------
entrada shape:  torch.Size([1, 7, 1])
tensor([[[0.6346],
         [0.0952],
     

### RNN con hidden

Veamos los parámetros del siguiente modelo con sus respectivas inputs y outputs:



![Red recurrente simple](https://docs.google.com/uc?id=1pWM5wlqYX8HSiTXz_Gg7KSOzvcxAQeQF)

link:
https://drive.google.com/file/d/1pWM5wlqYX8HSiTXz_Gg7KSOzvcxAQeQF/view?usp=drive_link


Parámetros/señales a ver su tamaño (agrege las necesarias):


```
# Entrada
x =

# hidden state
h =

# Salida
y =
h =

# parámetros
Wih =
Bih =

Whh =
Bhh =
```

In [11]:
input_size= 1
hidden_size= 3
num_layers= 1
largo_entrada = 7

model = SimpleRNN(input_size, hidden_size, num_layers)
teoria(model, largo_entrada)

------------------------------------------------------------------------------------
MODELO
------------------------------------------------------------------------------------
SimpleRNN(
  (rnn): RNN(1, 3, batch_first=True)
)
------------------------------------------------------------------------------------
PARAMETROS DEL MODELO
------------------------------------------------------------------------------------
Nombre del parámetro: 
rnn.weight_ih_l0
Tamaño del parámetro: 
torch.Size([3, 1])

Nombre del parámetro: 
rnn.weight_hh_l0
Tamaño del parámetro: 
torch.Size([3, 3])

Nombre del parámetro: 
rnn.bias_ih_l0
Tamaño del parámetro: 
torch.Size([3])

Nombre del parámetro: 
rnn.bias_hh_l0
Tamaño del parámetro: 
torch.Size([3])

------------------------------------------------------------------------------------
ENTRADA
------------------------------------------------------------------------------------
entrada shape:  torch.Size([1, 7, 1])
tensor([[[0.9249],
         [0.4229],
     

### RNN con 2 layers


Veamos los parámetros del siguiente modelo con sus respectivas inputs y outputs:



![Red recurrente simple](https://docs.google.com/uc?id=1mOmacJg5qE2B7KtAsqd--iCNknyD3_5J)

link:
https://drive.google.com/file/d/1mOmacJg5qE2B7KtAsqd--iCNknyD3_5J/view?usp=drive_link


Parámetros/señales a ver su tamaño (agrege las necesarias):


```
# Entrada
x =

# hidden state
h_l0 =

# Salida
y =
h_l0 =
h_l1 =

# parámetros
Wih_l0 =
Bih_l0 =

Whh_l0 =
Bhh_l0 =

Wih_l1 =
Bih_l1 =

Whh_l1 =
Bhh_l1 =
```

In [7]:
input_size= 1
hidden_size= 1
num_layers= 3
largo_entrada = 7

model = SimpleRNN(input_size, hidden_size, num_layers)
teoria(model, largo_entrada)

------------------------------------------------------------------------------------
MODELO
------------------------------------------------------------------------------------
SimpleRNN(
  (rnn): RNN(1, 1, num_layers=3, batch_first=True)
)
------------------------------------------------------------------------------------
PARAMETROS DEL MODELO
------------------------------------------------------------------------------------
Nombre del parámetro: 
rnn.weight_ih_l0
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.weight_hh_l0
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.bias_ih_l0
Tamaño del parámetro: 
torch.Size([1])

Nombre del parámetro: 
rnn.bias_hh_l0
Tamaño del parámetro: 
torch.Size([1])

Nombre del parámetro: 
rnn.weight_ih_l1
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.weight_hh_l1
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.bias_ih_l1
Tamaño del parámetro: 
torch.Size([1])

N

### RNN con input mutivariable


Veamos los parámetros del siguiente modelo con sus respectivas inputs y outputs:



![Red recurrente simple](https://docs.google.com/uc?id=1z0h38RWgxbtrMUazdPHvK3KZTCZFfmJR)

link:
https://drive.google.com/file/d/1z0h38RWgxbtrMUazdPHvK3KZTCZFfmJR/view?usp=drive_link


Parámetros/señales a ver su tamaño (agrege las necesarias):


```
# Entrada
x =

# hidden state
h =

# Salida
y =
h =

# parámetros
Wih =
Bih =

Whh =
Bhh =
```

In [8]:
input_size= 3
hidden_size= 1
num_layers= 1
largo_entrada = 7

model = SimpleRNN(input_size, hidden_size, num_layers)
teoria(model, largo_entrada, input_size= input_size)

------------------------------------------------------------------------------------
MODELO
------------------------------------------------------------------------------------
SimpleRNN(
  (rnn): RNN(3, 1, batch_first=True)
)
------------------------------------------------------------------------------------
PARAMETROS DEL MODELO
------------------------------------------------------------------------------------
Nombre del parámetro: 
rnn.weight_ih_l0
Tamaño del parámetro: 
torch.Size([1, 3])

Nombre del parámetro: 
rnn.weight_hh_l0
Tamaño del parámetro: 
torch.Size([1, 1])

Nombre del parámetro: 
rnn.bias_ih_l0
Tamaño del parámetro: 
torch.Size([1])

Nombre del parámetro: 
rnn.bias_hh_l0
Tamaño del parámetro: 
torch.Size([1])

------------------------------------------------------------------------------------
ENTRADA
------------------------------------------------------------------------------------
entrada shape:  torch.Size([1, 7, 3])
tensor([[[0.3775, 0.8642, 0.9925],
        

### RNN con varias cosas y batch size!

In [9]:
input_size= 2
hidden_size=3
num_layers=2

largo_entrada = 9
batch_size=4

model = SimpleRNN(input_size, hidden_size, num_layers)
teoria(model, largo_entrada, batch_size, input_size= input_size)

------------------------------------------------------------------------------------
MODELO
------------------------------------------------------------------------------------
SimpleRNN(
  (rnn): RNN(2, 3, num_layers=2, batch_first=True)
)
------------------------------------------------------------------------------------
PARAMETROS DEL MODELO
------------------------------------------------------------------------------------
Nombre del parámetro: 
rnn.weight_ih_l0
Tamaño del parámetro: 
torch.Size([3, 2])

Nombre del parámetro: 
rnn.weight_hh_l0
Tamaño del parámetro: 
torch.Size([3, 3])

Nombre del parámetro: 
rnn.bias_ih_l0
Tamaño del parámetro: 
torch.Size([3])

Nombre del parámetro: 
rnn.bias_hh_l0
Tamaño del parámetro: 
torch.Size([3])

Nombre del parámetro: 
rnn.weight_ih_l1
Tamaño del parámetro: 
torch.Size([3, 3])

Nombre del parámetro: 
rnn.weight_hh_l1
Tamaño del parámetro: 
torch.Size([3, 3])

Nombre del parámetro: 
rnn.bias_ih_l1
Tamaño del parámetro: 
torch.Size([3])

N

## EJERCICIO 1 - Complete el cuadro del powerpoint paras los siguientes 3 ejemplos:
```
EJEMPLO A
input_size = 2
batch_size = 16
hidden_size = 24
num_layer = 3
```

```
EJEMPLO B
input_size = 6
batch_size = 16
hidden_size = 24
num_layer = 1
```
```
EJEMPLO C
input_size = 10
batch_size = 64
hidden_size = 64
num_layer = 4
```

## EJERCICIO 2 - Implementar una RNN para clasificación de 5 clases dada una secuencia de datos:
- `input size = 2`.
- `hidden size= 40`.
- `num_layers = 2`.
- Agregar una `fully conected` al final con `n_out = nro clases`.
- Tomar como `input` de la `fc` el estado final de la rnn.
- Agregar por último una `softmax` para leer probabilidades.
- Probar funcionamiento del modelo haciendo un forward con un número rand sin entrenar la red.


![Red recurrente simple](https://docs.google.com/uc?id=1llbd9OArPRMAReI730fEtfmsN8VX3QfL)

link:
https://drive.google.com/file/d/1llbd9OArPRMAReI730fEtfmsN8VX3QfL/view?usp=drive_link